'use client';
import { useEffect, useState } from 'react';
import { AudioLines, House, ChartNoAxesCombined, Disc3, Heart, ArrowUpRight, ArrowRight, Info, ShieldCheck, Sparkles, Compass, Fingerprint, Waves, RefreshCw, Check, LockKeyhole, Search, X, Headphones, ChevronRight } from 'lucide-react';
import { SidebarProvider, SidebarMenu, SidebarMenuItem, SidebarMenuButton } from '@/components/ui/sidebar';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { tracks } from '@/lib/tracks';
import type { Analysis } from '@/lib/server/analysis';
const metricIcons = [Waves, Compass, Fingerprint, AudioLines];
const colors = ['#f379bb', '#b082fc', '#65bdfa', '#f2c96d'];
export default function Dashboard() {
 const [view,setView] = useState('home'); const [period,setPeriod] = useState('month');
 const [data,setData] = useState<Analysis|null>(null); const [busy,setBusy] = useState(true); const [error,setError] = useState(''); const [revision,setRevision] = useState(0);
 const [selected,setSelected] = useState(0); const [saved,setSaved] = useState<number[]>([]); const [query,setQuery] = useState(''); const [dialog,setDialog] = useState('');
 useEffect(()=>{ const controller = new AbortController(); setBusy(true); setError(''); fetch(`/api/analysis?period=${period}`,{signal:controller.signal}).then(r=>{if(!r.ok) throw new Error();return r.json()}).then(d=>setData(d as Analysis)).catch(e=>{if(e.name!=='AbortError')setError('Non siamo riusciti a caricare il confronto. Riprova.');}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return ()=>controller.abort(); },[period,revision]);
 const track=tracks[selected];
 const toggleSave=(i:number)=>setSaved(s=>s.includes(i)?s.filter(n=>n!==i):[...s,i]);
 const filtered=tracks.map((t,i)=>({...t,i})).filter(t=>(view!=='saved'||saved.includes(t.i))&&`${t.title} ${t.artist}`.toLowerCase().includes(query.toLowerCase()));
 return <SidebarProvider><div className="shell">
  <header className="topbar"><a className="brand" href="/" aria-label="Mitchometro home"><AudioLines/><span>Mitch<span className="gradient-text">ometro</span><small>La scienza (poco seria) del buon gusto musicale.</small></span></a><div className="header-actions"><span className="demo-pill">ANTEPRIMA DEMO</span><button className="connect" onClick={()=>setDialog('connect')}><Disc3 size={18}/> Collega Spotify <ArrowUpRight size={16}/></button></div></header>
  <aside className="side"><span className="eyebrow side-label">IL TUO UNIVERSO</span><SidebarMenu>{[{id:'home',label:'Panoramica',icon:House},{id:'stats',label:'Le tue statistiche',icon:ChartNoAxesCombined},{id:'match',label:'Il tuo match',icon:AudioLines},{id:'saved',label:'Brani salvati',icon:Heart}].map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton size="lg" aria-label={n.label} isActive={view===n.id} onClick={()=>{setView(n.id);setQuery('')}}><n.icon/><span>{n.label}</span>{n.id==='saved'&&saved.length>0&&<b>{saved.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="side-bottom"><div className="private-note"><ShieldCheck/><strong>Il riferimento è privato.</strong><p>Tu scopri il confronto.<br/>L’identità resta segreta.</p></div><blockquote>“Il buon gusto non è un’opinione,<br/>è un dato.”</blockquote><small>— Mitchometro, più o meno.</small><button className="text-button about" onClick={()=>setDialog('method')}>Come funziona <ArrowUpRight size={14}/></button></div></aside>
  <main className="main"><div className="page-heading"><div><div className="eyebrow">MENO ALGORITMI. PIÙ PERSONALITÀ.</div><h1>{view==='home'?'Il tuo gusto, senza filtri.':view==='match'?'Questione di sintonia.':view==='stats'?'Dentro i tuoi ascolti.':'Da riascoltare.'}</h1><p>{view==='saved'?'I tuoi preferiti di questa sessione demo.':'La tua musica ha qualcosa da dire. Vediamo cosa.'}</p></div><div className="period-controls"><Select value={period} onValueChange={setPeriod}><SelectTrigger aria-label="Periodo di analisi"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="month">Ultime 4 settimane</SelectItem><SelectItem value="semester">Ultimi 6 mesi</SelectItem><SelectItem value="year">Ultimi 12 mesi</SelectItem></SelectContent></Select><button className="icon-button" aria-label="Aggiorna analisi" disabled={busy} onClick={()=>setRevision(r=>r+1)}><RefreshCw size={17} className={busy?'spin':''}/></button></div></div>
  <div className="demo-banner"><span><Sparkles size={15}/><strong>Un assaggio del tuo Mitchometro.</strong> Stai esplorando dati dimostrativi, non un profilo Spotify reale.</span><button onClick={()=>setDialog('connect')}>Il tuo profilo <ArrowRight size={16}/></button></div>
  {error?<div className="error" role="alert">{error}<button onClick={()=>setRevision(r=>r+1)}>Riprova</button></div>:!data?<div className="loading" role="status"><AudioLines className="spin"/> Prepariamo il tuo universo musicale…</div>:<div className={busy?'results updating':'results'} aria-busy={busy}>
  {view==='home'&&<div className="hero-grid"><section className="panel feature"><div className="section-top"><h2><span className="mint"><AudioLines size={20}/></span> Nella tua rotazione</h2><span className="micro-label">SELEZIONE DEMO</span></div><div className="featured-song"><a href={track.source} target="_blank" rel="noreferrer" aria-label={`Copertina di ${track.album} su Apple Music`}><img className="cover" src={track.image} alt={`Copertina ${track.album}`} /></a><div className="song-info"><span className="tag">{track.genre}</span><h3>{track.title}</h3><p className="artist">{track.artist}</p><p>{track.album} · {track.year}</p><div className="song-actions"><a className="play-link" href={`https://open.spotify.com/search/${encodeURIComponent(track.artist+' '+track.title)}`} target="_blank" rel="noreferrer"><Disc3 size={17}/> Apri in Spotify <ArrowUpRight size={15}/></a><button className={`icon-button ${saved.includes(selected)?'liked':''}`} aria-label={saved.includes(selected)?'Rimuovi dai salvati':'Salva brano'} aria-pressed={saved.includes(selected)} onClick={()=>toggleSave(selected)}><Heart size={20} fill={saved.includes(selected)?'currentColor':'none'}/></button></div></div></div><div className="track-selector">{tracks.map((t,i)=><button key={t.title} onClick={()=>setSelected(i)} aria-label={`Mostra ${t.title}`} aria-pressed={i===selected} className={i===selected?'active':''}><span>0{i+1}</span><span>{t.artist}</span></button>)}</div><div className="feature-footer"><Headphones size={16}/><span>La colonna sonora della tua personalità.</span><span className="mint">Falla sentire.</span></div></section>
  <section className="panel score-panel"><div className="section-top"><h2><ChartNoAxesCombined size={20} className="mint"/> Indice di gusto</h2><button className="icon-button" aria-label="Come viene calcolato il punteggio" onClick={()=>setDialog('method')}><Info size={17}/></button></div><div className="gauge"><svg viewBox="0 0 340 220" aria-hidden="true"><defs><linearGradient id="scoreGradient"><stop stopColor="#8b60ff"/><stop offset="1" stopColor="#55e5bf"/></linearGradient></defs><path d="M 50 180 A 140 140 0 1 1 290 180" pathLength="120" className="gauge-track"/><path d="M 50 180 A 140 140 0 1 1 290 180" pathLength="120" strokeDasharray={`${data.score} 120`} className="gauge-value"/><line x1="289" y1="89" x2="309" y2="82" stroke="#e5e4f3" strokeWidth="2"/><text x="311" y="71">100</text></svg><div className="gauge-number"><strong>{data.score}</strong><span>/ 120</span></div><span className="gauge-zero">0</span><span className="gauge-max">120</span></div><h3>{data.score>=100?'Hai alzato il volume.':'Hai un bel sound.'}</h3><p>{data.score>=100?'Il tuo indice supera il riferimento.':'Personalità da vendere. Ancora spazio per stupire.'}</p><button className="baseline" onClick={()=>setDialog('method')}><LockKeyhole size={15}/><span>Il riferimento vale <b>100</b></span><Info size={14}/></button></section></div>}
  {(view==='home'||view==='stats')&&<><div className="metric-grid">{data.metrics.map((m,i)=>{const Icon=metricIcons[i];return <button key={m.key} className="panel metric" style={{'--metric':colors[i]} as React.CSSProperties} onClick={()=>setDialog(m.key)}><div><Icon/><h2>{m.name}</h2><ArrowUpRight size={15}/></div><div className="metric-number">{m.value}<small>/{m.key==='affinity'?'100':'120'}</small></div><div className="bar"><span style={{width:`${m.value/(m.key==='affinity'?100:120)*100}%`}}/></div><p>{m.detail}</p></button>})}</div><div className="insights-grid"><section className="panel insight"><div className="insight-icon good"><Sparkles/></div><div><span className="eyebrow mint">IL TUO PUNTO FORTE</span><h3>{data.strength.title}</h3><p>{data.strength.text}</p></div><span className="insight-score mint">{data.metrics[2].value}<small>/120</small></span></section><section className="panel insight"><div className="insight-icon warm"><Compass/></div><div><span className="eyebrow gold">IL PROSSIMO PASSO</span><h3>{data.weakness.title}</h3><p>{data.weakness.text}</p></div></section></div></>}
  {(view==='home'||view==='match'||view==='stats')&&<section className="panel matching"><div className="section-top"><h2><AudioLines size={21} className="purple"/>{view==='stats'?'La mappa dei tuoi ascolti':'Il tuo match con il riferimento'}</h2><span className="privacy-label"><ShieldCheck size={14}/> Identità protetta</span></div><div className="matching-body"><div className="match-summary"><div className="match-number">{data.match}<span>%</span></div><strong>Stessa frequenza.</strong><p>Affinità tra i generi del tuo profilo e il riferimento privato.</p><button className="text-button" onClick={()=>view==='home'?setView('match'):setDialog('match')}>Esplora il confronto <ArrowRight size={16}/></button></div><div className="genre-area"><Tabs defaultValue="genres"><TabsList variant="line"><TabsTrigger value="genres">I tuoi generi</TabsTrigger><TabsTrigger value="details">Il confronto</TabsTrigger></TabsList><TabsContent value="genres"><div className="genres">{data.genres.map((g,i)=><div className="genre" key={g.name}><div><span>{g.name}</span><b>{g.share}%</b></div><div className="bar"><span style={{width:`${g.share}%`,background:colors[i]}}/></div></div>)}</div></TabsContent><TabsContent value="details"><div className="comparison-detail"><div><span>Artisti nel campione</span><strong>{data.artists}</strong></div><div><span>Brani nel campione</span><strong>{data.tracks}</strong></div><p>Il match confronta la distribuzione dei generi, non il valore della tua musica. Gli ascolti e l’identità del riferimento non sono condivisi.</p></div></TabsContent></Tabs></div><div className="match-note"><div className="orb"><AudioLines size={32}/></div><strong>Due universi.<br/>Un punto d’incontro.</strong><p>La sintonia conta.<br/>La tua personalità, di più.</p></div></div></section>}
  {(view==='home'||view==='saved')&&<section className="recent"><div className="section-top"><h2><Disc3 size={22}/> {view==='saved'?'La tua selezione':'Nel profilo demo'}</h2><label className="search"><Search size={16}/><input aria-label="Cerca brani o artisti" placeholder="Cerca un brano o artista" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Cancella ricerca" onClick={()=>setQuery('')}><X size={14}/></button>}</label></div><div className="recent-grid">{filtered.map(t=><div className="recent-track" key={t.title}><button className="track-open" onClick={()=>{setSelected(t.i);setView('home');window.scrollTo({top:0,behavior:'smooth'})}}><img src={t.image} alt=""/><span><strong>{t.title}</strong><small>{t.artist}</small></span></button><button className={`icon-button ${saved.includes(t.i)?'liked':''}`} aria-label={`${saved.includes(t.i)?'Rimuovi':'Salva'} ${t.title}`} aria-pressed={saved.includes(t.i)} onClick={()=>toggleSave(t.i)}><Heart size={15} fill={saved.includes(t.i)?'currentColor':'none'}/></button></div>)}</div>{filtered.length===0&&<div className="empty"><Heart/><h3>{query?'Nessun brano trovato.':'Il tuo prossimo preferito ti aspetta.'}</h3><p>{query?'Prova un altro titolo o artista.':'Tocca il cuore accanto a un brano per ritrovarlo qui.'}</p><button className="text-button" onClick={()=>{setQuery('');if(!query)setView('home')}}>{query?'Cancella ricerca':'Esplora i brani'}<ArrowRight size={16}/></button></div>}</section>}
  </div>}
  <footer><span><AudioLines size={15}/> Mitchometro <small>v0.1 · demo</small></span><div><button onClick={()=>setDialog('method')}>Il metodo</button><button onClick={()=>setDialog('privacy')}>Privacy</button><span>Fatto con <Heart size={13}/> e un po’ di giudizio.</span></div></footer>
  </main>
  <Dialog open={!!dialog} onOpenChange={open=>!open&&setDialog('')}><DialogContent className="app-dialog"><DialogTitle>{dialog==='connect'?'Il tuo Spotify, prossimamente.':dialog==='method'?'Il gusto è personale. Il metodo, trasparente.':dialog==='privacy'?'La tua musica resta tua.':dialog==='match'?'Come funziona il match':data?.metrics.find(m=>m.key===dialog)?.name}</DialogTitle><DialogDescription asChild><div className="dialog-copy">{dialog==='connect'?<><p>Questa anteprima usa esclusivamente dati dimostrativi. Nessun account è collegato e non vengono richieste credenziali.</p><p>Il collegamento reale richiede la configurazione dell’app Spotify, l’autorizzazione dei profili e la verifica dell’ammissibilità del confronto secondo le regole Spotify.</p><a href="https://developer.spotify.com/policy" target="_blank" rel="noreferrer">Leggi la policy Spotify <ArrowUpRight size={14}/></a></>:dialog==='method'?<><p>Scala da 0 a 120. Il profilo di riferimento vale 100. Il punteggio parte dalla media di varietà, scoperta e identità. L’affinità applica un fattore compreso tra 0,8 e 1: media × (0,8 + 0,2 × match / 100).</p><p>I primi tre indicatori sono normalizzati sul riferimento e limitati a 120. L’affinità misura la sovrapposizione dei generi ed è limitata a 100. Il riferimento confrontato con sé stesso vale 100. Con tre indicatori a 120 e match al 100%, il punteggio raggiunge 120.</p><p>Questo è un modello provvisorio su dati sintetici: non misura una qualità musicale oggettiva. I punteggi e i consigli non riguardano gli artisti mostrati.</p></>:dialog==='privacy'?<><p>Questa demo non accede a Spotify e non raccoglie dati personali. I brani salvati restano solo nella memoria di questa sessione e scompaiono ricaricando la pagina.</p><p>Il riferimento dimostrativo viene elaborato sul server. Il browser riceve solo risultati aggregati, mai identità, credenziali o cronologia del riferimento.</p><p>Le copertine vengono caricate da Apple Music, che riceve la normale richiesta del browser. Nessun ascolto viene riprodotto nell’app.</p></>:dialog==='match'?<><p>Il match è la somma delle quote in comune tra le distribuzioni di generi, da 0 a 100%. Una sintonia del 100% indica distribuzioni uguali.</p><p>Puoi esplorare i tuoi generi. Il profilo di riferimento e i suoi ascolti individuali restano privati sul server.</p></>:<><p>{data?.metrics.find(m=>m.key===dialog)?.description}</p><p>Indicatore calcolato su dati dimostrativi. {dialog==='affinity'?'Massimo 100%.':'Il riferimento vale 100; il massimo è 120.'}</p></>}</div></DialogDescription><button className="connect dialog-done" onClick={()=>setDialog('')}><Check size={16}/> Ho capito</button></DialogContent></Dialog>
 </div></SidebarProvider>
}
