'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { AudioLines, House, ChartNoAxesCombined, Disc3, Heart, ArrowUpRight, ArrowRight, Info, ShieldCheck, Sparkles, Compass, Fingerprint, Waves, RefreshCw, Check, LockKeyhole, Search, X, Headphones, ChevronRight, FileUp } from 'lucide-react';
import { SidebarProvider, SidebarMenu, SidebarMenuItem, SidebarMenuButton } from '@/components/ui/sidebar';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { tracks } from '@/lib/tracks';
import type { Analysis } from '@/lib/server/analysis';
import UserMusicSetup from '@/components/user-music-setup';
import RotationFeature from '@/components/rotation-feature';
const metricIcons = [Waves, Compass, Fingerprint, AudioLines];
const colors = ['#f379bb', '#b082fc', '#65bdfa', '#f2c96d'];

export default function Dashboard({ viewerName, viewerIsMaster }: { viewerName: string; viewerIsMaster: boolean }) {
 const [view,setView] = useState('home'); const [period,setPeriod] = useState('month');
 const [data,setData] = useState<Analysis|null>(null); const [busy,setBusy] = useState(true); const [error,setError] = useState(''); const [revision,setRevision] = useState(0);
 const [selected,setSelected] = useState(0); const [saved,setSaved] = useState<number[]>([]); const [query,setQuery] = useState(''); const [dialog,setDialog] = useState('');
 useEffect(()=>{ const controller = new AbortController(); fetch(`/api/analysis?period=${period}`,{signal:controller.signal}).then(r=>{if(!r.ok) throw new Error();return r.json()}).then(d=>setData(d as Analysis)).catch(e=>{if(e.name!=='AbortError')setError('Non siamo riusciti a caricare il confronto. Riprova.');}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return ()=>controller.abort(); },[period,revision]);
 const toggleSave=(i:number)=>setSaved(s=>s.includes(i)?s.filter(n=>n!==i):[...s,i]);
 const filtered=tracks.map((t,i)=>({...t,i})).filter(t=>(view!=='saved'||saved.includes(t.i))&&`${t.title} ${t.artist}`.toLowerCase().includes(query.toLowerCase()));
 return <SidebarProvider><div className="shell">
  <header className="topbar"><Link className="brand" href="/" aria-label="Mitchometro home"><AudioLines/><span>Mitch<span className="gradient-text">ometro</span><small>La scienza (poco seria) del buon gusto musicale.</small></span></Link><div className="header-actions"><span className="demo-pill">{data?.mode === 'real' ? 'CRONOLOGIA CARICATA' : 'ANTEPRIMA DEMO'}</span><span className="viewer-name" title={viewerName}>{viewerName}</span><a className="viewer-signout" href="/signout-with-chatgpt?return_to=%2F" title="Esci da Mitchometro">Esci</a>{viewerIsMaster && <a className="owner-control" aria-label="Apri il pannello admin" href="/admin"><LockKeyhole size={16}/><span>Admin</span></a>}<button className="connect" onClick={() => setDialog('connect')}><FileUp size={18}/> Analizza la tua musica <ArrowUpRight size={16}/></button></div></header>
  <aside className="side"><span className="eyebrow side-label">IL TUO UNIVERSO</span><SidebarMenu>{[{id:'home',label:'Panoramica',icon:House},{id:'stats',label:'Le tue statistiche',icon:ChartNoAxesCombined},{id:'match',label:'Il tuo match',icon:AudioLines},{id:'saved',label:'Brani salvati',icon:Heart}].map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton size="lg" aria-label={n.label} isActive={view===n.id} onClick={()=>{setView(n.id);setQuery('')}}><n.icon/><span>{n.label}</span>{n.id==='saved'&&saved.length>0&&<b>{saved.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="side-bottom"><div className="private-note"><ShieldCheck/><strong>Il riferimento è privato.</strong><p>Tu scopri il confronto.<br/>L’identità resta segreta.</p></div><blockquote>“Il buon gusto non è un’opinione,<br/>è un dato.”</blockquote><small>— Mitchometro, più o meno.</small>{viewerIsMaster && <a className="text-button about" href="/admin">Pannello admin <ArrowUpRight size={14}/></a>}<button className="text-button about" onClick={()=>setDialog('method')}>Come funziona <ArrowUpRight size={14}/></button></div></aside>
  <main className="main"><div className="page-heading"><div><div className="eyebrow">MENO ALGORITMI. PIÙ PERSONALITÀ.</div><h1>{view==='home'?'Il tuo gusto, senza filtri.':view==='match'?'Questione di sintonia.':view==='stats'?'Dentro i tuoi ascolti.':'Da riascoltare.'}</h1><p>{view==='saved'?'I tuoi preferiti di questa sessione demo.':'La tua musica ha qualcosa da dire. Vediamo cosa.'}</p></div><div className="period-controls"><Select value={period} onValueChange={value=>{setPeriod(value);setBusy(true);setError('')}}><SelectTrigger aria-label="Periodo di analisi"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="month">Ultime 4 settimane</SelectItem><SelectItem value="semester">Ultimi 6 mesi</SelectItem><SelectItem value="year">Ultimi 12 mesi</SelectItem></SelectContent></Select><button className="icon-button" aria-label="Aggiorna analisi" disabled={busy} onClick={()=>{setBusy(true);setError('');setRevision(r=>r+1)}}><RefreshCw size={17} className={busy?'spin':''}/></button></div></div>
  <div className="demo-banner"><span><Sparkles size={15}/><strong>{data?.mode === 'real' ? 'Confronto dalla cronologia estesa.' : 'Anteprima dimostrativa.'}</strong> {data?.mode === 'real' ? 'Il punteggio usa la tua cronologia estesa e il riferimento privato.' : 'Carica la tua cronologia estesa per confrontarla con il riferimento privato.'}</span><button onClick={() => setDialog('connect')}>Carica la cronologia <ArrowRight size={16}/></button></div>
  {error?<div className="error" role="alert">{error}<button onClick={()=>{setBusy(true);setError('');setRevision(r=>r+1)}}>Riprova</button></div>:!data?<div className="loading" role="status"><AudioLines className="spin"/> Prepariamo il tuo universo musicale…</div>:<div className={busy?'results updating':'results'} aria-busy={busy}>
  {view==='home'&&<div className="hero-grid"><RotationFeature revision={revision} selected={selected} setSelected={setSelected} saved={saved} toggleSave={toggleSave}/>
  <section className="panel score-panel"><div className="section-top"><h2><ChartNoAxesCombined size={20} className="mint"/> Indice di gusto</h2><button className="icon-button" aria-label="Come viene calcolato il punteggio" onClick={()=>setDialog('method')}><Info size={17}/></button></div><div className="gauge"><svg viewBox="0 0 340 220" aria-hidden="true"><defs><linearGradient id="scoreGradient"><stop stopColor="#8b60ff"/><stop offset="1" stopColor="#55e5bf"/></linearGradient></defs><path d="M 50 180 A 140 140 0 1 1 290 180" pathLength="120" className="gauge-track"/><path d="M 50 180 A 140 140 0 1 1 290 180" pathLength="120" strokeDasharray={`${data.score} 120`} className="gauge-value"/><line x1="289" y1="89" x2="309" y2="82" stroke="#e5e4f3" strokeWidth="2"/><text x="311" y="71">100</text></svg><div className="gauge-number"><strong>{data.score}</strong><span>/ 120</span></div><span className="gauge-zero">0</span><span className="gauge-max">120</span></div><h3>{data.scoreMessage.title}</h3><p>{data.scoreMessage.body}</p><button className="baseline" onClick={()=>setDialog('method')}><LockKeyhole size={15}/><span>Il riferimento vale <b>100</b></span><Info size={14}/></button></section></div>}
  {(view==='home'||view==='stats')&&<><div className="metric-grid">{data.metrics.map((m,i)=>{const Icon=metricIcons[i];return <button key={m.key} className="panel metric" style={{'--metric':colors[i]} as React.CSSProperties} onClick={()=>setDialog(m.key)}><div><Icon/><h2>{m.name}</h2><ArrowUpRight size={15}/></div><div className="metric-number">{m.value}<small>/{m.key==='affinity'?'100':'120'}</small></div><div className="bar"><span style={{width:`${m.value/(m.key==='affinity'?100:120)*100}%`}}/></div><p>{m.detail}</p></button>})}</div><div className="insights-grid"><section className="panel insight"><div className="insight-icon good"><Sparkles/></div><div><span className="eyebrow mint">IL TUO PUNTO FORTE</span><h3>{data.strength.title}</h3><p>{data.strength.text}</p></div><span className="insight-score mint">{data.metrics[2].value}<small>/120</small></span></section><section className="panel insight"><div className="insight-icon warm"><Compass/></div><div><span className="eyebrow gold">IL PROSSIMO PASSO</span><h3>{data.weakness.title}</h3><p>{data.weakness.text}</p></div></section></div></>}
  {(view==='home'||view==='match'||view==='stats')&&<section className="panel matching"><div className="section-top"><h2><AudioLines size={21} className="purple"/>{view==='stats'?'La mappa dei tuoi ascolti':'Il tuo match con il riferimento'}</h2><span className="privacy-label"><ShieldCheck size={14}/> Identità protetta</span></div><div className="matching-body"><div className="match-summary"><div className="match-number">{data.match}<span>%</span></div><strong>Stessa frequenza.</strong><p>{data.mode === 'real' ? 'Affinità tra gli artisti ascoltati e il riferimento privato.' : 'Affinità dimostrativa tra i generi del profilo e il riferimento privato.'}</p><button className="text-button" onClick={()=>view==='home'?setView('match'):setDialog('match')}>Esplora il confronto <ArrowRight size={16}/></button></div><div className="genre-area"><Tabs defaultValue="genres"><TabsList variant="line"><TabsTrigger value="genres">{data.mode === 'real' ? 'I tuoi artisti' : 'I tuoi generi'}</TabsTrigger><TabsTrigger value="details">Il confronto</TabsTrigger></TabsList><TabsContent value="genres"><div className="genres">{data.genres.map((g,i)=><div className="genre" key={g.name}><div><span>{g.name}</span><b>{g.share}%</b></div><div className="bar"><span style={{width:`${g.share}%`,background:colors[i]}}/></div></div>)}</div></TabsContent><TabsContent value="details"><div className="comparison-detail"><div><span>Artisti nel campione</span><strong>{data.artists}</strong></div><div><span>Brani nel campione</span><strong>{data.tracks}</strong></div><p>{data.mode === 'real' ? 'Il match confronta la distribuzione degli ascolti per artista. Gli ascolti e l’identità del riferimento non sono condivisi.' : 'Il match è dimostrativo. Gli ascolti e l’identità del riferimento non sono condivisi.'}</p></div></TabsContent></Tabs></div><div className="match-note"><div className="orb"><AudioLines size={32}/></div><strong>Due universi.<br/>Un punto d’incontro.</strong><p>La sintonia conta.<br/>La tua personalità, di più.</p></div></div></section>}
  {(view==='home'||view==='saved')&&<section className="recent"><div className="section-top"><h2><Disc3 size={22}/> {view==='saved'?'La tua selezione':'Nel profilo demo'}</h2><label className="search"><Search size={16}/><input aria-label="Cerca brani o artisti" placeholder="Cerca un brano o artista" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Cancella ricerca" onClick={()=>setQuery('')}><X size={14}/></button>}</label></div><div className="recent-grid">{filtered.map(t=><div className="recent-track" key={t.title}><button className="track-open" onClick={()=>{setSelected(t.i);setView('home');window.scrollTo({top:0,behavior:'smooth'})}}><img src={t.image} alt=""/><span><strong>{t.title}</strong><small>{t.artist}</small></span></button><button className={`icon-button ${saved.includes(t.i)?'liked':''}`} aria-label={`${saved.includes(t.i)?'Rimuovi':'Salva'} ${t.title}`} aria-pressed={saved.includes(t.i)} onClick={()=>toggleSave(t.i)}><Heart size={15} fill={saved.includes(t.i)?'currentColor':'none'}/></button></div>)}</div>{filtered.length===0&&<div className="empty"><Heart/><h3>{query?'Nessun brano trovato.':'Il tuo prossimo preferito ti aspetta.'}</h3><p>{query?'Prova un altro titolo o artista.':'Tocca il cuore accanto a un brano per ritrovarlo qui.'}</p><button className="text-button" onClick={()=>{setQuery('');if(!query)setView('home')}}>{query?'Cancella ricerca':'Esplora i brani'}<ArrowRight size={16}/></button></div>}</section>}
  </div>}
  <footer><span><AudioLines size={15}/> Mitchometro <small>{data?.mode === 'real' ? 'v0.2 · cronologia' : 'v0.2 · demo'}</small></span><div><button onClick={()=>setDialog('method')}>Il metodo</button><a href="/privacy">Privacy</a><span>Fatto con <Heart size={13}/> e un po’ di giudizio.</span></div></footer>
  </main>
  <Dialog open={!!dialog} onOpenChange={open=>!open&&setDialog('')}>
    <DialogContent className={dialog==='connect'?'app-dialog music-dialog':'app-dialog'}>
      <DialogTitle>{dialog==='connect'?'Carica la tua cronologia':dialog==='method'?'Come funziona il punteggio':dialog==='privacy'?'La tua musica resta tua.':dialog==='match'?'Come funziona il match':data?.metrics.find(m=>m.key===dialog)?.name}</DialogTitle>
      <DialogDescription asChild><div className="dialog-copy">
        {dialog==='connect'?<UserMusicSetup onUpdated={()=>{setBusy(true);setRevision(r=>r+1)}}/>:
        dialog==='method'?data?.mode==='real'?<><p>Il tuo punteggio confronta gli artisti della tua cronologia con quelli del profilo master, che vale 100. Varietà, scoperta e identità sono rapporti rispetto al riferimento, limitati a 120.</p><p>L’affinità misura la sovrapposizione delle quote di ascolto degli artisti. La media dei tre indicatori viene moltiplicata per (0,8 + 0,2 × affinità / 100), poi si applicano eventuali bonus o malus impostati dall’admin. Il risultato è limitato a 0–120.</p><p>Consideriamo solo i brani ascoltati per almeno 30 secondi negli ultimi 28 giorni, 6 mesi o 12 mesi. Il punteggio è un gioco di somiglianze, non un giudizio oggettivo sulla musica.</p></>:<p>Stai vedendo un esempio. Carica la tua cronologia estesa per il confronto; serve anche il riferimento master.</p>:
        dialog==='privacy'?<><p>Leggiamo i file JSON nel browser e inviamo solo conteggi per artista e indicatori aggregati. I file originali, indirizzi IP e dati sul dispositivo non vengono salvati.</p><p>Puoi sostituire o cancellare la cronologia caricata dalle opzioni di analisi. Il profilo master completo è accessibile solo all’admin. Un suo brano casuale alla volta può comparire nella dashboard.</p></>:
        dialog==='match'?<p>{data?.mode==='real'?'Il match confronta quanto spesso ascolti ciascun artista rispetto al riferimento privato. 100% significa distribuzioni uguali.':'Il confronto mostrato è dimostrativo. Carica le cronologie per vedere il match reale.'}</p>:
        <><p>{data?.metrics.find(m=>m.key===dialog)?.description}</p><p>{data?.mode==='real'?'Indicatore calcolato dai tuoi ascolti.':'Indicatore dimostrativo.'} {dialog==='affinity'?'Massimo 100%.':'Il riferimento vale 100; il massimo è 120.'}</p></>}
      </div></DialogDescription>
      <button className="connect dialog-done" onClick={()=>setDialog('')}><Check size={16}/> Chiudi</button>
    </DialogContent>
  </Dialog>
 </div></SidebarProvider>
}
