'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { AudioLines, House, ChartNoAxesCombined, ArrowUpRight, ArrowRight, Info, ShieldCheck, Sparkles, Compass, Fingerprint, Waves, RefreshCw, Check, LockKeyhole, X, FileUp } from 'lucide-react';
import { SidebarProvider, SidebarMenu, SidebarMenuItem, SidebarMenuButton } from '@/components/ui/sidebar';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import type { Analysis } from '@/lib/server/analysis';
import UserMusicSetup from '@/components/user-music-setup';
import RotationFeature from '@/components/rotation-feature';
const metricIcons = [Waves, Compass, Fingerprint, AudioLines];
const colors = ['#f379bb', '#b082fc', '#65bdfa', '#f2c96d'];

export default function Dashboard({ viewerName, viewerIsMaster, initialHasUpload }: { viewerName: string; viewerIsMaster: boolean; initialHasUpload: boolean }) {
 const [view,setView] = useState('home'); const [period,setPeriod] = useState('month');
 const [hasUpload,setHasUpload] = useState(initialHasUpload);
 const [data,setData] = useState<Analysis|null>(null); const [busy,setBusy] = useState(true); const [error,setError] = useState(''); const [revision,setRevision] = useState(0); const [periodNotice,setPeriodNotice] = useState('');
 const [selected,setSelected] = useState(0); const [saved,setSaved] = useState<number[]>([]); const [dialog,setDialog] = useState('');
 useEffect(()=>{ if(!hasUpload)return; const controller = new AbortController(); fetch(`/api/analysis?period=${period}`,{signal:controller.signal}).then(r=>{if(!r.ok) throw new Error();return r.json()}).then(raw=>{const d=raw as Analysis & {periodFallbackReason?:string};if(d.period!==period){const labels={month:'gli ultimi 30 giorni',year:'l’ultimo anno',forever:'tutta la cronologia'};if(d.periodFallbackReason==='reload-history'){setPeriodNotice('Per il giudizio “Da sempre”, sia tu sia il Sommo Maestro dovete ripresentare tutti i JSON della cronologia estesa. Sua Santità esaminerà intanto l’ultimo anno.');}else{setPeriodNotice(`Le prove del periodo scelto non bastano al verdetto: il Maestro giudicherà ${labels[d.period]}.`);setPeriod(d.period);}}setData(d)}).catch(e=>{if(e.name!=='AbortError')setError('Non siamo riusciti a convocare il Maestro. Riprova.');}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return ()=>controller.abort(); },[hasUpload,period,revision]);
 const toggleSave=(i:number)=>setSaved(s=>s.includes(i)?s.filter(n=>n!==i):[...s,i]);
 const onMusicUpdated=async()=>{try{const response=await fetch('/api/history',{cache:'no-store'});if(!response.ok)return;const status=await response.json() as {mine:unknown|null};const ready=!!status.mine;setHasUpload(ready);setData(ready?data:null);setBusy(ready);setRevision(r=>r+1);setDialog('');}catch{setRevision(r=>r+1)}};
 if(!hasUpload)return <div className="onboarding-shell">
  <header className="topbar onboarding-topbar"><Link className="brand" href="/" aria-label="Mitchometro home"><AudioLines/><span>Mitch<span className="gradient-text">ometro</span><small>Il tribunale supremo delle tue scelte musicali.</small></span></Link><div className="header-actions"><span className="viewer-name" title={viewerName}>{viewerName}</span><form action="/api/auth/logout" method="post"><button className="viewer-signout" title="Esci da Mitchometro">Esci</button></form>{viewerIsMaster&&<a className="owner-control" aria-label="Apri il pannello admin" href="/admin"><LockKeyhole size={16}/><span>Admin</span></a>}<button className="connect" onClick={()=>setDialog('connect')}><FileUp size={18}/> Presenta le prove <ArrowUpRight size={16}/></button></div></header>
  <main className="onboarding-main">
   <section className="onboarding-intro"><div className="eyebrow mint">IL GIUDIZIO FINALE DI MITCH</div><h1>Il Sommo Maestro è pronto.<br/>Mancano solo le prove.</h1><p className="onboarding-lead">Per ricevere il verdetto di <strong>Sua Santità del Punk</strong>, sottoponi la tua musica al giudizio: fai l’upload dei dati di ascolto Spotify.</p><div className="onboarding-steps"><div><span>1</span><p>Apri la pagina <a href="https://www.spotify.com/account/privacy/" target="_blank" rel="noreferrer">Privacy del tuo account Spotify <ArrowUpRight size={13}/></a>.</p></div><div><span>2</span><p>Richiedi la <strong>Cronologia di ascolto estesa</strong>, l’archivio completo su cui il Maestro pronuncerà la sentenza.</p></div><div><span>3</span><p>Quando ricevi lo ZIP, estrailo e presenta al tribunale tutti i file JSON della cronologia musicale.</p></div></div><button className="connect onboarding-cta" onClick={()=>setDialog('connect')}><FileUp size={19}/> Presenta le prove al Maestro <ArrowRight size={17}/></button></section>
   <figure className="dashboard-example"><div className="example-label"><Sparkles size={15}/> ESEMPIO DEL VERDETTO</div><div className="example-title-patch">Il Giudizio Finale di Mitch</div><img src="/mitchometro-dashboard-example.jpeg" alt="Esempio del Giudizio Finale di Mitch dopo l’analisi della cronologia Spotify"/><figcaption>Il tribunale si apre dopo il caricamento e il confronto con il sacro canone privato del Maestro.</figcaption></figure>
   <div className="onboarding-rotation"><RotationFeature revision={revision} selected={selected} setSelected={setSelected} saved={saved} toggleSave={toggleSave}/></div>
   <footer><span><AudioLines size={15}/> Mitchometro <small>v0.3</small></span><div><a href="/privacy">Privacy</a><span>Il giudizio del Maestro è insindacabile.</span></div></footer>
  </main>
  <Dialog open={dialog==='connect'} onOpenChange={open=>!open&&setDialog('')}><DialogContent className="app-dialog music-dialog"><DialogTitle>Presenta le prove a Sua Santità</DialogTitle><DialogDescription asChild><div className="dialog-copy"><UserMusicSetup onUpdated={onMusicUpdated}/></div></DialogDescription><button className="connect dialog-done" onClick={()=>setDialog('')}><Check size={16}/> Chiudi l’udienza</button></DialogContent></Dialog>
 </div>;
 return <SidebarProvider><div className="shell">
  <header className="topbar"><Link className="brand" href="/" aria-label="Mitchometro home"><AudioLines/><span>Mitch<span className="gradient-text">ometro</span><small>Il tribunale supremo delle tue scelte musicali.</small></span></Link><div className="header-actions"><span className="demo-pill">{data?.mode === 'real' ? 'IL MAESTRO HA PARLATO' : 'UDIENZA DI PROVA'}</span><span className="viewer-name" title={viewerName}>{viewerName}</span><form action="/api/auth/logout" method="post"><button className="viewer-signout" title="Esci da Mitchometro">Esci</button></form>{viewerIsMaster && <a className="owner-control" aria-label="Apri il pannello admin" href="/admin"><LockKeyhole size={16}/><span>Admin</span></a>}<button className="connect" onClick={() => setDialog('connect')}><FileUp size={18}/> Presenta nuove prove <ArrowUpRight size={16}/></button></div></header>
  <aside className="side"><span className="eyebrow side-label">IL TRIBUNALE DI MITCH</span><SidebarMenu>{[{id:'home',label:'Il verdetto',icon:House},{id:'stats',label:'Le prove',icon:ChartNoAxesCombined},{id:'match',label:'Udienza col Maestro',icon:AudioLines}].map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton size="lg" aria-label={n.label} isActive={view===n.id} onClick={()=>setView(n.id)}><n.icon/><span>{n.label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="side-bottom"><div className="private-note"><ShieldCheck/><strong>Il sacro canone è segreto.</strong><p>Tu ricevi la sentenza.<br/>Il Maestro resta avvolto nel mistero.</p></div><blockquote>“Mitch ascolta tutto.<br/>Mitch non dimentica niente.”</blockquote><small>— Antico testo apocrifo</small>{viewerIsMaster && <a className="text-button about" href="/admin">Pannello del Gran Maestro <ArrowUpRight size={14}/></a>}<button className="text-button about" onClick={()=>setDialog('method')}>Come giudica Mitch <ArrowUpRight size={14}/></button></div></aside>
  <main className="main"><div className="page-heading"><div><div className="eyebrow">MITCH TI GIUDICA. SENZA APPELLO.</div><h1>{view==='home'?'Il Giudizio Finale di Mitch':view==='match'?'Udienza con Sua Santità del Punk':'Le prove a tuo carico'}</h1><p>Il Sommo Maestro ha esaminato i tuoi ascolti. Preparati alla sentenza.</p></div><div className="period-controls"><Select value={period} onValueChange={value=>{setPeriod(value);setPeriodNotice('');setBusy(true);setError('')}}><SelectTrigger aria-label="Periodo sottoposto al giudizio"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="month">Ultimi 30 giorni</SelectItem><SelectItem value="year">Ultimo anno</SelectItem><SelectItem value="forever">Da sempre</SelectItem></SelectContent></Select><button className="icon-button" aria-label="Chiedi un nuovo verdetto" disabled={busy} onClick={()=>{setBusy(true);setError('');setRevision(r=>r+1)}}><RefreshCw size={17} className={busy?'spin':''}/></button></div></div>
  {periodNotice && <div className="period-notice" role="status">{periodNotice}<button aria-label="Chiudi avviso" onClick={()=>setPeriodNotice('')}><X size={15}/></button></div>}
  <div className="demo-banner"><span><Sparkles size={15}/><strong>{data?.mode === 'real' ? 'Il Maestro ha esaminato le prove.' : 'Udienza dimostrativa.'}</strong> {data?.mode === 'real' ? 'Il verdetto confronta la tua cronologia con il sacro canone privato di Mitch.' : 'Presenta la cronologia estesa per ricevere il vero Giudizio Finale.'}</span><button onClick={() => setDialog('connect')}>Presenta la cronologia <ArrowRight size={16}/></button></div>
  {error?<div className="error" role="alert">Il tribunale è momentaneamente indisposto. {error}<button onClick={()=>{setBusy(true);setError('');setRevision(r=>r+1)}}>Riconvoca Mitch</button></div>:!data?<div className="loading" role="status"><AudioLines className="spin"/> Sua Santità del Punk sta esaminando le prove…</div>:<div className={busy?'results updating':'results'} aria-busy={busy}>
  {view==='home'&&<div className="hero-grid"><RotationFeature revision={revision} selected={selected} setSelected={setSelected} saved={saved} toggleSave={toggleSave}/>
  <section className="panel score-panel"><div className="section-top"><h2><ChartNoAxesCombined size={20} className="mint"/> Il Giudizio Finale di Mitch</h2><button className="icon-button" aria-label="Come Sua Santità calcola il verdetto" onClick={()=>setDialog('method')}><Info size={17}/></button></div><div className="gauge"><svg viewBox="0 0 340 220" aria-hidden="true"><defs><linearGradient id="scoreGradient"><stop stopColor="#8b60ff"/><stop offset="1" stopColor="#55e5bf"/></linearGradient></defs><path d="M 50 180 A 140 140 0 1 1 290 180" pathLength="120" className="gauge-track"/><path d="M 50 180 A 140 140 0 1 1 290 180" pathLength="120" strokeDasharray={`${data.score} 120`} className="gauge-value"/><line x1="289" y1="89" x2="309" y2="82" stroke="#e5e4f3" strokeWidth="2"/><text x="311" y="71">100</text></svg><div className="gauge-number"><strong>{data.score}</strong><span>/ 120</span></div><span className="gauge-zero">0</span><span className="gauge-max">120</span></div><h3>{data.scoreMessage.title}</h3><p>{data.scoreMessage.body}</p><button className="baseline" onClick={()=>setDialog('method')}><LockKeyhole size={15}/><span>Il sacro canone del Maestro vale <b>100</b></span><Info size={14}/></button></section></div>}
  {(view==='home'||view==='stats')&&<><div className="metric-grid">{data.metrics.map((m,i)=>{const Icon=metricIcons[i];return <button key={m.key} className="panel metric" style={{'--metric':colors[i]} as React.CSSProperties} onClick={()=>setDialog(m.key)}><div><Icon/><h2>{m.name}</h2><ArrowUpRight size={15}/></div><div className="metric-number">{m.value}<small>/{m.key==='affinity'?'100':'120'}</small></div><div className="bar"><span style={{width:`${m.value/(m.key==='affinity'?100:120)*100}%`}}/></div><p>{m.detail}</p></button>})}</div><div className="insights-grid"><section className="panel insight"><div className="insight-icon good"><Sparkles/></div><div><span className="eyebrow mint">IL TUO PUNTO FORTE</span><h3>{data.strength.title}</h3><p>{data.strength.text}</p></div><span className="insight-score mint">{data.metrics[2].value}<small>/120</small></span></section><section className="panel insight"><div className="insight-icon warm"><Compass/></div><div><span className="eyebrow gold">IL PROSSIMO PASSO</span><h3>{data.weakness.title}</h3><p>{data.weakness.text}</p></div></section></div></>}
  {(view==='home'||view==='match'||view==='stats')&&<section className="panel matching"><div className="section-top"><h2><AudioLines size={21} className="purple"/>{view==='stats'?'Le tavole sacre dei tuoi ascolti':'La tua sintonia con il Maestro'}</h2><span className="privacy-label"><ShieldCheck size={14}/> Canone segreto</span></div><div className="matching-body"><div className="match-summary"><div className="match-number">{data.match}<span>%</span></div><strong>Il Maestro concede udienza.</strong><p>{data.mode === 'real' ? 'Affinità tra i tuoi artisti e il sacro canone privato di Mitch.' : 'Simulazione della tua sintonia con il Gran Sacerdote del Volume.'}</p><button className="text-button" onClick={()=>view==='home'?setView('match'):setDialog('match')}>Consulta gli atti <ArrowRight size={16}/></button></div><div className="comparison-detail comparison-evidence"><div className="comparison-grid"><div className="comparison-stat"><span>Gruppi e artisti condivisi</span><strong>{data.comparison.sharedArtists}</strong></div><div className="comparison-stat"><span>Brani condivisi nell’intera cronologia</span><strong>{data.comparison.sharedTracks ?? '—'}</strong></div><div className="comparison-stat"><span>Tu: ascolti su artisti comuni</span><strong>{data.comparison.userSharedPlayShare}%</strong></div><div className="comparison-stat"><span>Maestro: ascolti sugli stessi artisti</span><strong>{data.comparison.masterSharedPlayShare}%</strong></div><div className="comparison-stat"><span>Artisti solo nel tuo repertorio</span><strong>{data.comparison.userOnlyArtists}</strong></div><div className="comparison-stat"><span>Artisti esclusivi del Maestro</span><strong>{data.comparison.masterOnlyArtists}</strong></div></div>{data.comparison.sharedArtistNames.length>0&&<div className="shared-artists"><span>Testimoni in comune</span><div>{data.comparison.sharedArtistNames.map(name=><b key={name}>{name}</b>)}</div></div>}<p>{data.comparison.sharedTracks===null?'Per attivare il confronto completo dei brani, sia il Maestro sia il fedele devono ripresentare la cronologia con il nuovo sistema.':'Il confronto considera tutti i brani unici presenti nelle due cronologie caricate.'} Il catalogo del Maestro resta segreto.</p></div><div className="match-note"><div className="orb"><AudioLines size={32}/></div><strong>Due universi.<br/>Un solo giudice.</strong><p>Mitch ascolta.<br/>Mitch sentenzia.</p></div></div></section>}
  </div>}
  <footer><span><AudioLines size={15}/> Mitchometro <small>{data?.mode === 'real' ? 'v0.3 · verdetto' : 'v0.3 · udienza demo'}</small></span><div><button onClick={()=>setDialog('method')}>La dottrina del Maestro</button><a href="/privacy">Privacy</a><span>Mitch ha giudicato. Tu puoi solo ascoltare.</span></div></footer>
  </main>
  <Dialog open={!!dialog} onOpenChange={open=>!open&&setDialog('')}>
    <DialogContent className={dialog==='connect'?'app-dialog music-dialog':'app-dialog'}>
      <DialogTitle>{dialog==='connect'?'Presenta le prove a Sua Santità':dialog==='method'?'La dottrina del Giudizio Finale':dialog==='privacy'?'Le tue prove restano tue.':dialog==='match'?'Come Mitch misura la sintonia':data?.metrics.find(m=>m.key===dialog)?.name}</DialogTitle>
      <DialogDescription asChild><div className="dialog-copy">
        {dialog==='connect'?<UserMusicSetup onUpdated={onMusicUpdated}/>:
        dialog==='method'?data?.mode==='real'?<><p>Il Giudizio Finale confronta gli artisti della tua cronologia con il sacro canone del Maestro, che per decreto vale 100. Repertorio, scoperta e identità sono rapporti rispetto al suo profilo, limitati a 120.</p><p>La sintonia misura la sovrapposizione delle quote di ascolto. Sua Santità del Punk combina i tre indicatori con l’affinità e applica i bonus o malus decisi dalla cabina di regia. La sentenza finale resta tra 0 e 120.</p><p>Il tribunale considera soltanto brani ascoltati per almeno 30 secondi negli ultimi 30 giorni, nell’ultimo anno o nell’intera cronologia. Il verdetto è un gioco di somiglianze: perfino il Sommo Maestro ammette, sottovoce, che il gusto non è una scienza esatta.</p></>:<p>Questa è un’udienza dimostrativa. Presenta la cronologia estesa e attendi che il Maestro pronunci il vero verdetto.</p>:
        dialog==='privacy'?<><p>Il tribunale legge i file JSON nel browser e invia conteggi per artista, indicatori aggregati e impronte tecniche non leggibili dei brani. I file originali, i titoli degli utenti, gli indirizzi IP e i dati sul dispositivo non vengono salvati.</p><p>Puoi sostituire o ritirare le prove dalle opzioni di analisi. Il catalogo completo del Maestro resta segreto; una sua reliquia musicale casuale alla volta può comparire nella dashboard.</p></>:
        dialog==='match'?<p>{data?.mode==='real'?'Mitch confronta quanto spesso ascolti ciascun artista con il suo sacro canone privato. 100% significa che i due repertori hanno la stessa distribuzione.':'Questa sintonia è dimostrativa. Presenta le prove per l’udienza reale.'}</p>:
        <><p>{data?.metrics.find(m=>m.key===dialog)?.description}</p><p>{data?.mode==='real'?'Indicatore decretato dai tuoi ascolti.':'Indicatore dell’udienza dimostrativa.'} {dialog==='affinity'?'Massimo 100%.':'Il sacro canone del Maestro vale 100; il massimo concesso è 120.'}</p></>}
      </div></DialogDescription>
      <button className="connect dialog-done" onClick={()=>setDialog('')}><Check size={16}/> Chiudi l’udienza</button>
    </DialogContent>
  </Dialog>
 </div></SidebarProvider>
}
